# Pin name action command file

# Start of element U1
ChangePinName(U1, unknown, unknown)
ChangePinName(U1, unknown, unknown)
ChangePinName(U1, 3, Y)
ChangePinName(U1, 2, B)
ChangePinName(U1, 1, A)
ChangePinName(U1, unknown, unknown)
ChangePinName(U1, unknown, unknown)
ChangePinName(U1, 3, Y)
ChangePinName(U1, 2, B)
ChangePinName(U1, 1, A)

# Start of element U?
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 10, B-)
ChangePinName(U?, 12, M-)
ChangePinName(U?, 11, M+)
ChangePinName(U?, 9, B+)
ChangePinName(U?, 8, GND)
ChangePinName(U?, 7, VCC)
ChangePinName(U?, 6, L_IS)
ChangePinName(U?, 5, R_IS)
ChangePinName(U?, 4, L_EN)
ChangePinName(U?, 3, R_EN)
ChangePinName(U?, 2, LPWM)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 1, 1)
ChangePinName(U?, 2, LPWM)
ChangePinName(U?, 1, 1)
